FROM maven:3-eclipse-temurin-21 AS cache
COPY ./src /tmp/src
COPY ./pom.xml /tmp/pom.xml
WORKDIR /tmp
RUN mvn package -DskipTests

FROM scratch
LABEL org.opencontainers.image.source=https://github.com/scc-digitalhub/openmetadata-java-connector 
COPY --from=cache /root/.m2 /root/.m2